[terminal]
[terminal.shell]
program = "/usr/bin/zsh"

[window]
# padding = { x = 10, y = 10 }
dynamic_padding = true

[font]
normal = { family = "JetBrainsMonoNL Nerd Font"}
size = 14

[colors]
[colors.primary]
background = "#212123"
foreground = "#f2f0e5"

[colors.normal]
black   = "#212123"
red     = '#b45252'
green   = '#8ab060'
yellow  = '#d3a068'
blue    = '#4b80ca'
magenta = '#6a536e'
cyan    = '#68c2d3'
white   = '#b8b5b9'

[colors.bright]
black   = '#868188'
# red     = '#F07178'
green   = '#c2d368'
yellow  = '#ede19e'
# blue    = '#59C2FF'
magenta = '#cf8acb'
cyan    = '#a2dcc7'
white   = '#f2f0e5'
