[[paths]]
srcPath = "/home/elias/.config/nvim/"
dstPath = "/home/elias/projects/perso/dotfiles/config/nvim/"

[[paths]]
srcPath = "/home/elias/.config/alacritty/"
dstPath = "/home/elias/projects/perso/dotfiles/config/alacritty/"

[[paths]]
srcPath = "/home/elias/.config/rofi/"
dstPath = "/home/elias/projects/perso/dotfiles/config/rofi/"

[[paths]]
srcPath = "/home/elias/.config/dunst/"
dstPath = "/home/elias/projects/perso/dotfiles/config/dunst/"

[[paths]]
srcPath = "/home/elias/.config/fastfetch/"
dstPath = "/home/elias/projects/perso/dotfiles/config/fastfetch/"

[[paths]]
srcPath = "/home/elias/.config/hypr/"
dstPath = "/home/elias/projects/perso/dotfiles/config/hypr/"

[[paths]]
srcPath = "/home/elias/.config/waybar/"
dstPath = "/home/elias/projects/perso/dotfiles/config/waybar/"

[[paths]]
srcPath = "/home/elias/.zshrc"
dstPath = "/home/elias/projects/perso/dotfiles/config/zsh/zshrc"

[[paths]]
srcPath = "/home/elias/.config/systemd/user/spotify-notify.service"
dstPath = "/home/elias/projects/perso/dotfiles/config/systemd/spotify-notify/spotify-notify.service"

[[paths]]
srcPath = "/home/elias/projects/perso/spotify-notify/"
dstPath = "/home/elias/projects/perso/dotfiles/config/systemd/spotify-notify/"

[[paths]]
srcPath = "/home/elias/.config/files-saver/config.toml"
dstPath = "/home/elias/projects/perso/dotfiles/config/files-saver/config.toml"

[[paths]]
srcPath = "/home/elias/projects/perso/files-saver/"
dstPath = "/home/elias/projects/perso/dotfiles/config/files-saver/"
